grails-app/domain/uk/ac/ed/bric/elearn/vle/Lecture.groovy
package uk.ac.ed.bric.elearn.vle

class Lecture {

    String name
    String code
    Integer orderNo
    Boolean isVisible
	String description
	String authors 
	String editors
	String learningObjectives
    Date dateCreated
    Date lastUpdated

    String toString() {
        return name
    }
    
    static belongsTo = [ module : Module ]
    static hasOne = [ lectureFile : LectureFile ]
    static hasMany = [ contentFiles : ContentFile, tests : Test ]
 
    static constraints = {
        name blank:false, nullable:false
        code blank:true, nullable:true, unique:true
        orderNo blank:false, nullable:false, unique:['module']
        isVisible blank:false, nullable:false
    	description blank:false, nullable:false
    	authors blank:true, nullable:true
    	editors blank:true, nullable:true
    	learningObjectives blank:true, nullable:true
        lectureFile blank:true, nullable:true, unique:true
        contentFiles blank:true, nullable:true
    }

    static mapping = {
		learningObjectives type: "text"
        contentFiles lazy:false, fetch: "join"
	}
}

grails-app/controllers/uk/ac/ed/bric/elearn/vle/LectureController.groovy
package uk.ac.ed.bric.elearn.vle

import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import uk.ac.ed.bric.elearn.vle.FileCommand

@Transactional(readOnly = true)
class LectureController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE", uploadLectureFile: "POST", deleteLectureFile: "DELETE"]

    def fileService

    @Secured('ROLE_ADMIN') 
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Lecture.list(params), model:[lectureCount: Lecture.count()]
    }

    @Secured('ROLE_ADMIN') 
    def show(Lecture lecture) {
        respond lecture
    }

    @Secured('ROLE_ADMIN') 
    def create() {
        respond new Lecture(params)
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def save(Lecture lecture) {
        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (lecture.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond lecture.errors, view:'create', model: [module: lecture.module, course: lecture.module.course]
            return
        }

        lecture.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'lecture.label', default: 'Lecture'), lecture.id])
                redirect lecture
            }
            '*' { respond lecture, [status: CREATED] }
        }
    }

    @Secured('ROLE_ADMIN') 
    def edit(Lecture lecture) {
        respond lecture
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def update(Lecture lecture) {

        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (lecture.hasErrors()) {
            transactionStatus.setRollbackOnly()
            render view:'edit', model: [lecture: lecture, module: lecture.module]
            return
        }

        lecture.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'lecture.label', default: 'Lecture'), lecture.id])
                redirect controller: "lecture", action:"edit", id: lecture.id, method:"GET"
            }
            '*'{ respond lecture, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def delete(Lecture lecture) {

        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        lecture.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'lecture.label', default: 'Lecture'), lecture.id])
                redirect controller: "module", action:"show", id: lecture.module.id, method:"GET"
            }
            '*'{ render status: NO_CONTENT }

        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'lecture.label', default: 'Lecture'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def addLectureFile(Lecture lecture) {
        FileCommand cmd = new FileCommand()
        render view:"addLectureFile", model:[lecture:lecture, fileCommand:cmd]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def addContentFile(Lecture lecture) {
        ContentFileCommand cmd = new ContentFileCommand()
        render view:"addContentFile", model:[lecture:lecture, contentFileCommand:cmd]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def uploadLectureFile(FileCommand command) {
        Lecture lecture = Lecture.get(params.lectureId)
        String name = params.uploadedLectureFileName
        if(command.hasErrors()) {
            render view: 'addLectureFile', model:[lecture:lecture, fileCommand:command]
            return
        }
 
        fileService.saveFile(command, lecture, name)
        render view:"show", model:[lecture:lecture]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def uploadContentFile(ContentFileCommand command) {
        Lecture lecture = Lecture.get(params.lectureId)
        String name = params.uploadedContentFileName
        int type = params.int('uploadedContentFileType')
        if(command.hasErrors()) {
            render view: 'addContentFile', model:[lecture:lecture, contentFileCommand:command]
            return
        }
 
        fileService.saveFile2(command, lecture, name, type)
        render view:"show", model:[lecture:lecture]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def uploadLectureFile2(FileCommand command) {
        Lecture lecture = Lecture.get(params.lectureId)
        String name = params.uploadedLectureFileName
        if(command.hasErrors()) {
            render view: 'edit', model:[lecture:lecture, fileCommand:command]
            return
        }
 
        fileService.saveFile(command, lecture, name)
        render view:"edit", model:[lecture:lecture]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def uploadContentFile2(ContentFileCommand command) {
        Lecture lecture = Lecture.get(params.lectureId)
        String name = params.uploadedContentFileName
        int type = params.int('uploadedContentFileType')
        if(command.hasErrors()) {
            render view: 'edit', model:[lecture:lecture, contentFileCommand:command]
            return
        }
 
        fileService.saveFile2(command, lecture, name, type)
        render view:"edit", model:[lecture:lecture]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def updateLectureFileName(Lecture lecture) {

        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (lecture.hasErrors()) {
            transactionStatus.setRollbackOnly()
            render view:'edit', model: [lecture: lecture, lectureFile: lecture.lectureFile]
            return
        }

        fileService.updateFileName(lecture, params.lectureFileName)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'lecture.label', default: 'Lecture File Name')])
                redirect controller: "lecture", action:"edit", id: lecture.id, method:"GET"
            }
            '*'{ respond lecture, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def deleteLectureFile(Lecture lecture) {

        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        fileService.deleteFile(lecture)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'lecture.label', default: 'Lecture File')])
                redirect controller: "lecture", action:"addLectureFile", id: lecture.id, method:"GET"
            }
            '*'{ render status: NO_CONTENT }

        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def deleteLectureFile2(Lecture lecture) {

        if (lecture == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        fileService.deleteFile(lecture)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'lecture.label', default: 'Lecture File')])
                redirect controller: "lecture", action:"edit", id: lecture.id, method:"GET"
            }
            '*'{ render status: NO_CONTENT }

        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def deleteContentFile() {

        ContentFile contentFile = ContentFile.get(params.int('contentFileId'))
        
        if (contentFile == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        Lecture lecture = contentFile.owner
        fileService.deleteContentFile(lecture, contentFile)

        if(contentFileSaveFail(contentFile)) {
            render template:"content_files", model:[lecture:lecture]
            return     
        }

        render template:"content_files", model:[lecture:lecture]

    }

    @Transactional
    def contentFileSaveFail(domainObject) {
        def result = true
        if(domainObject.hasErrors()) {
            transactionStatus.setRollbackOnly()
            flash.ajaxerror = errorsToString(domainObject) 
            result = true
        } else {
            result = false
        }
        return result
    }

    def errorsToString(domainObject) {
        def message = new StringBuilder()
        for(fieldErrors in domainObject.errors) {
            for(error in fieldErrors.allErrors) {
                message.append("\n\t").append(messageSource.getMessage(error, Locale.getDefault()))
            }
        }
        message.toString()       
    }

    @Secured('ROLE_ADMIN') 
    def listTests(Lecture lecture) {
        respond lecture
    }
}

grails-app/views/lecture/_content_files.gsp
<div id="optionsDiv">
	
	<g:if test="${flash.ajaxerror}">
		<div class="alert alert-dismissable alert-danger">
			<button type="button" class="close" data-dismiss="alert">×</button>
			${flash.ajaxerror}
		</div>
	</g:if>

	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-8">
			<p><strong>Current supporting files:</strong></p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-1"></div>
			<div class="col-md-9">
				<g:if test="${lecture.contentFiles}">
					<ul class="list-group">
						<g:each in="${lecture.contentFiles}" var="contentFile">
						 	<li class="list-group-item">${contentFile.fileName} (display text: ${contentFile.name}) 
						 	<div class="delete-buttons">
						 	<a href="#" class="pull-right text-danger" onClick="deleteOption('${contentFile?.id}')">
						 	<button class="btn btn-danger">
						 	<i class="fa fa-trash-o" aria-hidden="true"></i> Delete
						 	</button>
						 	</a>
						 	</div>
							</li>
						</g:each>
					</ul>
				</g:if>
				<g:else>
					<p><em>No supporting files added yet</em></p>
				</g:else>
			</div>
		</div>
	</div>

</div>

grails-app/views/lecture/_form_fields.gsp
	<div class="col-md-12">

        <div class="form-group">
            <label for="name" class="col-md-2 control-label">Name <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:lecture, field:'name', 'has-warning')}">
                    <g:field type="text" name="name" bean="${lecture}" value="${lecture?.name}" class="form-control" />
             </div>
        </div>

        <div class="form-group">
             <label for="module" class="col-md-2 control-label">Module </label>
             <div class="col-md-10">
                <div class="form-text"><f:display bean="${lecture}" property="module.name" class="form-control" /></div>
             </div>
        </div>

        <div class="form-group">
            <label for="orderNo" class="col-md-2 control-label">Order no. <span class="required-indicator">*</span></label>
             <div class="col-md-2 ${hasErrors(bean:lecture, field:'orderNo', 'has-warning')}">
                    <g:field type="number" min="1" max="100" name="orderNo" bean="${lecture}" value="${lecture?.orderNo}" class="form-control" />
             </div>
        </div>
<%--
		<div class="form-group">
	        <label for="code" class="col-md-2 control-label">Code <span class="required-indicator">*</span></label>
	         <div class="col-md-10 ${hasErrors(bean:lecture,field:'code', 'has-warning')}">
	         		<g:field type="text" name="code" bean="${lecture}" value="${lecture?.code}" class="form-control" />
	         </div>
	    </div>
--%>
        <div class="form-group">
            <label for="isVisible" class="col-md-2 control-label">Published </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'isVisible', 'has-warning')}">
                    <div class="form-checkbox"><f:widget bean="${lecture}" property="isVisible" class="form-check-input" /></div>
             </div>
        </div>
       
	    <div class="form-group">
            <label for="description" class="col-md-2 control-label">Description <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'description', 'has-warning')}">
             		<g:field type="text" name="description" bean="${lecture}" value="${lecture?.description}" class="form-control"/>
             		
             </div>
        </div>

        <div class="form-group">
            <label for="authors" class="col-md-2 control-label">Author(s) </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'authors', 'has-warning')}">
                    <g:field type="text" name="authors" bean="${lecture}" value="${lecture?.authors}" class="form-control"/>
                    
             </div>
        </div>

        <div class="form-group">
            <label for="editors" class="col-md-2 control-label">Editor(s) </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'editors', 'has-warning')}">
                    <g:field type="text" name="editors" bean="${lecture}" value="${lecture?.editors}" class="form-control"/>
                    
             </div>
        </div>
       
        <div class="form-group">
        <label for="learningObjectives" class="col-md-2 control-label">Learning Objectives </label>
            <div class="col-md-10">
                <ckeditor:editor name="learningObjectives" toolbar="custom" height="300px" width="100%">
                    ${lecture?.learningObjectives}
                </ckeditor:editor>
            </div>
        </div>

<%--
        <div class="form-group">
        <label for="lectureContent" class="col-md-2 control-label">Lecture Content </label>
            <div class="col-md-10">
                <ckeditor:editor name="lectureContent" toolbar="custom" height="300px" width="100%">
                    ${lecture?.lectureContent}
                </ckeditor:editor>
            </div>
        </div>
--%>

    </div>

grails-app/views/lecture/_form_fields_create.gsp
<div class="col-md-12">

        <div class="form-group">
            <label for="name" class="col-md-2 control-label">Name <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:lecture, field:'name', 'has-warning')}">
                    <g:field type="text" name="name" bean="${lecture}" value="" class="form-control" />
             </div>
        </div>

        <div class="form-group">
            <label for="name" class="col-md-2 control-label">Module <span class="required-indicator">*</span></label>
            <div class="col-md-10 ${hasErrors(bean:lecture, field:'module', 'has-warning')}">
            <f:widget bean="${lecture}" property="module" class="form-check-input" />
             </div>
        </div>

        <div class="form-group">
            <label for="orderNo" class="col-md-2 control-label">Order no. <span class="required-indicator">*</span></label>
             <div class="col-md-2 ${hasErrors(bean:lecture, field:'orderNo', 'has-warning')}">
                    <g:field type="number" min="1" max="100" name="orderNo" bean="${lecture}" value="" class="form-control" />
             </div>
        </div>
<%--
		<div class="form-group">
	        <label for="code" class="col-md-2 control-label">Code <span class="required-indicator">*</span></label>
	         <div class="col-md-10 ${hasErrors(bean:lecture,field:'code', 'has-warning')}">
	         		<g:field type="text" name="code" bean="${lecture}" value="" class="form-control" />
	         </div>
	    </div>
--%>
        <div class="form-group">
            <label for="isVisible" class="col-md-2 control-label">Published </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'isVisible', 'has-warning')}">
                    <div class="form-checkbox"><f:widget bean="${lecture}" property="isVisible" class="form-check-input" /></div>
             </div>
        </div>
       
	    <div class="form-group">
            <label for="description" class="col-md-2 control-label">Description <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'description', 'has-warning')}">
             		<g:field type="text" name="description" bean="${lecture}" value="" class="form-control"/>
             		
             </div>
        </div>

        <div class="form-group">
            <label for="authors" class="col-md-2 control-label">Author(s) </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'authors', 'has-warning')}">
                    <g:field type="text" name="authors" bean="${lecture}" value="" class="form-control"/>
                    
             </div>
        </div>

        <div class="form-group">
            <label for="editors" class="col-md-2 control-label">Editor(s) </label>
             <div class="col-md-10 ${hasErrors(bean:lecture,field:'editors', 'has-warning')}">
                    <g:field type="text" name="editors" bean="${lecture}" value="" class="form-control"/>
                    
             </div>
        </div>
       
        <div class="form-group">
        <label for="learningObjectives" class="col-md-2 control-label">Learning Objectives </label>
            <div class="col-md-10">
                <ckeditor:editor name="learningObjectives" toolbar="custom" height="300px" width="100%">

                </ckeditor:editor>
            </div>
        </div>

<%--
        <div class="form-group">
        <label for="lectureContent" class="col-md-2 control-label">Lecture Content </label>
            <div class="col-md-10">
                <ckeditor:editor name="lectureContent" toolbar="custom" height="300px" width="100%">

                </ckeditor:editor>
            </div>
        </div>
--%>

    </div>

grails-app/views/lecture/_form_fields_file.gsp
    <div class="col-md-12">

        <div class="form-group">
            <label for="lectureFile.name" class="col-md-2 control-label">Name </label>
             <div class="col-md-10 ${hasErrors(bean:lecture, field:'lectureFile.name', 'has-warning')}">

                 <f:display bean="lecture" property="lectureFile.name"> 
                 <g:textField name="lectureFileName" value="${lecture.lectureFile.name}" class="form-control" />
                 </f:display>

             </div>
        </div>
       
    </div>

grails-app/views/lecture/addContentFile.gsp
 <!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'lecture.label', default: 'Lecture')}" />
        <title><g:message code="default.addFile.label" args="[entityName]" /></title>

        <script type="text/javascript">
            
            function deleteOption(contentFileId) {
                var params = {contentFileId:contentFileId}
                handleOption(params,"${grailsApplication.config.vle.url}/lecture/deleteContentFile")
            };

            function handleOption(params, action) {
                var data = $.param(params)
                var response
                $.post(action,data, function(response) {
                    $('#optionsDiv').html( response )
                })  
                .fail(function() {
                    $( "#optionsDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };
    
    </script>
    </head>
    <body>

        <p><g:link controller="course" action="index">Courses</g:link> > <g:link controller="course" action="show" id="${lecture.module.course.id}"><f:display bean="lecture" property="module.course.name" /></g:link> > <g:link controller="module" action="show" id="${lecture.module.id}"><f:display bean="lecture" property="module.name" /></g:link> > Add Supporting Files to Lecture</p>

        <div class="panel panel-primary">
            <div class="panel-heading"><g:message code="default.addContentFiles.label" args="[entityName]" /></div>
            <div class="panel-body">
                <ul class="errors" role="alert">
                <g:hasErrors bean="${contentFileCommand}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${contentFileCommand}" var="error">
                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                        </g:eachError>
                    </div>
                </g:hasErrors>
                
                </ul>


                <p>
                <b>${lecture.name}</b>
                </p>
                
                <p>
                These are supporting files for the lecture and can be in .doc, .docx, .pdf or .mp3 file formats.
                </p>

                <g:uploadForm name="upload" action="uploadContentFile" method="post" controller="Lecture">
 
                <g:hiddenField name="lectureId" value="${lecture.id}" />
 
                <input type="file" class="btn btn-default" name="uploadedContentFile" />
                <br/>
                Type of file (mandatory): <select name="uploadedContentFileType" required>
                <option value="">Select one:</option>
                <option value="0">Slides</option>
                <option value="1">Audio</option>
                <option value="2">Resources</option>
                <option value="3">Other</option>
                </select>
                <br/>
                <br/>
                Display text for file (optional): <input type="text" name="uploadedContentFileName" />
                <br/>

                <div class="btn-toolbar">
                     <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'lecture.lectureFile.upload.label', default: 'Upload')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Upload</button>
                     <g:link controller="module" action="show" id="${lecture.module.id}" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link>
                </div>

                </g:uploadForm>
                <br/>
                <g:render template="content_files" bean="${lecture}"/>


            </div>
        </div>


    </body>
</html>

grails-app/views/lecture/addLectureFile.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'lecture.label', default: 'Lecture')}" />
        <title><g:message code="default.addFile.label" args="[entityName]" /></title>

    </head>
    <body>     

        <p><g:link controller="course" action="index">Courses</g:link> > <g:link controller="course" action="show" id="${lecture.module.course.id}"><f:display bean="lecture" property="module.course.name" /></g:link> > <g:link controller="module" action="show" id="${lecture.module.id}"><f:display bean="lecture" property="module.name" /></g:link> > Add File to Lecture</p>

    	<div class="panel panel-primary">
        	<div class="panel-heading"><g:message code="default.addLectureFile.label" args="[entityName]" /></div>
        	<div class="panel-body">
             	<ul class="errors" role="alert">
                <g:hasErrors bean="${fileCommand}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${fileCommand}" var="error">
                			<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                		</g:eachError>
                    </div>
                </g:hasErrors>
                
                </ul>


                <p>
                <b>${lecture.name}</b>
                </p>
                
                <g:if test="${lecture.lectureFile}">
                <p>
                This lecture already has a main content file. This must be removed if a new file is added.
            	</p>
            	<p>
				File: ${lecture.lectureFile.fileName}
				</p>
				<g:form controller="lecture" id="${lecture.id}" method="DELETE">
        		<g:actionSubmit action="deleteLectureFile" value="Delete lecture file" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        		</g:form>
                <div class="btn-toolbar">
                     <g:link controller="module" action="show" id="${lecture.module.id}" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link>
                </div>
				</g:if>

                <g:else>
				<p>
				This is the main content of the lecture and should be an Adobe Presenter package in .zip file format.
				</p>

        		<g:uploadForm name="upload" action="uploadLectureFile" method="post" controller="Lecture">
 
            	<g:hiddenField name="lectureId" value="${lecture.id}" />
 
            	<input type="file" class="btn btn-default" name="uploadedFile" />
            	<br/>
                Display text for file (optional): <input type="text" name="uploadedLectureFileName" />
                <br/>

                <div class="btn-toolbar">
                     <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'lecture.lectureFile.upload.label', default: 'Upload')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Upload</button>
                     <g:link controller="module" action="show" id="${lecture.module.id}" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link>
                </div>

        		</g:uploadForm>
                </g:else>
        	</div>
        </div>

    </body>
</html>

grails-app/views/lecture/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'lecture.label', default: 'Lecture')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-lecture" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-lecture" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${lectureList}" />

            <div class="pagination">
                <g:paginate total="${lectureCount ?: 0}" />
            </div>
        </div>

                 <div  role="main">
            <h2>Lectures</h2>
            
            <table class="table table-striped">
            <thead>
                    <tr>
                    
                        <g:sortableColumn property="name" title="Name" />
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                <g:each in="${lectureList}" status="i" var="lectureInstance">
                    <tr>
                    
                        <td>${fieldValue(bean: lectureInstance, field: "name")}</td>
                        <td><g:link action="show" id="${lectureInstance.id}">Show</g:link></td>
                    </tr>
                </g:each>
                </tbody>
            </table>
            <div class="pagination">
                <p:bootstrapPagination total="${lectureCount ?: 0}" domainBean="uk.ac.ed.bric.elearn.vle.Lecture" />
            </div>
        </div>
               
    </body>
</html>