grails-app/domain/uk/ac/ed/bric/elearn/vle/Course.groovy
package uk.ac.ed.bric.elearn.vle

class Course {

	String name
	String code
	Integer orderNo
	Boolean isVisible
	String welcomePage
	String staffPage
	Date dateCreated
    Date lastUpdated

    String toString() {
        return name
    }

 	static hasMany = [ modules : Module ]

    static constraints = {
    	 name blank:false, nullable:false
    	 code blank:true, nullable:true, unique:true
    	 orderNo blank:false, nullable:false, unique:true
    	 isVisible blank:false, nullable:false
    	 welcomePage blank:true, nullable:true
    	 staffPage blank:true, nullable:true
    }

    static mapping = {
        welcomePage type: "text"
        staffPage type: "text"
    }
}

grails-app/controllers/uk/ac/ed/bric/elearn/vle/CourseController.groovy
package uk.ac.ed.bric.elearn.vle

import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import uk.ac.ed.bric.elearn.User

@Transactional(readOnly = true)
class CourseController {

    def springSecurityService
    def courseService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_USER','ROLE_ADMIN']) 
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Course.list(params), model:[courseCount: Course.count()]
    }

    @Secured(['ROLE_USER','ROLE_ADMIN']) 
    def show(Course course) {

        //find if logged-in user is enrolled on selected course
        User user = springSecurityService.currentUser

        sec.ifAnyGranted(roles:'ROLE_USER')
        {
            CourseEnrolment enrolment = courseService.findCourseEnrolment(course, user)
            if(!enrolment && user) {
                //show no enrolment page
                render (view: "notEnrolled", model:[course:course])
                return
            }
            else {
                //show course content 
                respond course
            }
        }
        sec.ifAnyGranted(roles:'ROLE_ADMIN')
        {
                //show course content 
                respond course
        }
    }

    @Secured('ROLE_ADMIN') 
    def create() {
        respond new Course(params)
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def save(Course course) {
        if (course == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (course.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond course.errors, view:'create'
            return
        }

        course.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'course.label', default: 'Course'), course.id])
                redirect course
            }
            '*' { respond course, [status: CREATED] }
        }
    }

    @Secured('ROLE_ADMIN') 
    def edit(Course course) {
        respond course
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def update(Course course) {
        if (course == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (course.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond course.errors, view:'edit'
            return
        }

        course.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'course.label', default: 'Course'), course.id])
                redirect course
            }
            '*'{ respond course, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def delete(Course course) {

        if (course == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        course.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'course.label', default: 'Course'), course.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /* Enrolment methods are used by REST client (User Admin app) */
    @Secured('ROLE_ADMIN') 
    def list() {
        respond Course.list(params)
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def enrol() {
        Course course = Course.get(params.courseId.toLong())
        User user = User.get(params.userId.toLong())
        
        CourseEnrolment enrolment = new CourseEnrolment(course:course, user:user)
        enrolment.validate()
        if(enrolment.hasErrors()) {
            log.error "Validating enrolment had errors: ${enrolment.errors}"
            render status: BAD_REQUEST
            return
        }

        enrolment.save flush:true
        if(enrolment.hasErrors()) {
            log.error "Saving enrolment had errors: ${enrolment.errors}"
            render status: BAD_REQUEST
            return
        }

        render status: OK
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def withdraw() {
        Course course = Course.get(params.courseId.toLong())
        User user = User.get(params.userId.toLong())

        log.info "withdraw $user from $course"

        CourseEnrolment enrolment = courseService.findCourseEnrolment(course, user)
        if(!enrolment) {
            render status: NOT_FOUND
            return
        }
        enrolment.delete flush:true
        
        render status: OK
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def findUserCourses() {
        User user = User.get(params.userId.toLong())
        def enrolments = courseService.findEnrolmentsByUser(user)
        render(contentType: "text/xml") {
            userEnrolments {
                for (e in enrolments) {
                    enrolment(user:e.user.id, courseId:e.course.id, courseName:e.course.name )
                }
            }
        }
    }


    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'course.label', default: 'Course'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    @Secured(['ROLE_USER','ROLE_ADMIN'])
    def showWelcomePage(Course course)
    {
        respond course
    }

    @Secured(['ROLE_USER','ROLE_ADMIN'])
    def showStaffPage(Course course)
    {
        respond course
    }
}

grails-app/views/course/_form_fields.gsp
<div class="col-md-12">

        <div class="form-group">
            <label for="name" class="col-md-2 control-label">Name <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:course, field:'name', 'has-warning')}">
                    <g:field type="text" name="name" bean="${course}" value="${course?.name}" class="form-control" />
             </div>
        </div>

        <div class="form-group">
            <label for="orderNo" class="col-md-2 control-label">Order no. <span class="required-indicator">*</span></label>
             <div class="col-md-2 ${hasErrors(bean:course, field:'orderNo', 'has-warning')}">
                    <g:field type="number" min="1" max="100" name="orderNo" bean="${course}" value="${course?.orderNo}" class="form-control" />
             </div>
        </div>
<%--
		<div class="form-group">
	        <label for="code" class="col-md-2 control-label">Code <span class="required-indicator">*</span></label>
	         <div class="col-md-10 ${hasErrors(bean:course,field:'code', 'has-warning')}">
	         		<g:field type="text" name="code" bean="${course}" value="${course?.code}" class="form-control" />
	         </div>
	    </div>
--%>
        <div class="form-group">
            <label for="isVisible" class="col-md-2 control-label">Published </label>
             <div class="col-md-10 ${hasErrors(bean:course,field:'isVisible', 'has-warning')}">
                    <div class="form-checkbox"><f:widget bean="${course}" property="isVisible" class="form-check-input" /></div>
             </div>
        </div>
       
        <div class="form-group">
            <label for="description" class="col-md-2 control-label">Welcome page </label>
             <div class="col-md-10">
                <ckeditor:editor name="welcomePage" toolbar="custom" height="300px" width="100%">
                    ${course?.welcomePage}
                </ckeditor:editor>
             </div>
        </div>

        <div class="form-group">
            <label for="description" class="col-md-2 control-label">Staff page </label>
             <div class="col-md-10">
                <ckeditor:editor name="staffPage" toolbar="custom" height="300px" width="100%">
                    ${course?.staffPage}
                </ckeditor:editor>
             </div>
        </div>

   </div>

grails-app/views/course/_form_fields_create.gsp
<div class="col-md-12">

        <div class="form-group">
            <label for="name" class="col-md-2 control-label">Name <span class="required-indicator">*</span></label>
             <div class="col-md-10 ${hasErrors(bean:course, field:'name', 'has-warning')}">
                    <g:field type="text" name="name" bean="${course}" value="" class="form-control" />
             </div>
        </div>

        <div class="form-group">
            <label for="orderNo" class="col-md-2 control-label">Order no. <span class="required-indicator">*</span></label>
             <div class="col-md-2 ${hasErrors(bean:course, field:'orderNo', 'has-warning')}">
                    <g:field type="number" min="1" max="100" name="orderNo" bean="${course}" value="" class="form-control" />
             </div>
        </div>
<%--
		<div class="form-group">
	        <label for="code" class="col-md-2 control-label">Code <span class="required-indicator">*</span></label>
	         <div class="col-md-10 ${hasErrors(bean:course,field:'code', 'has-warning')}">
	         		<g:field type="text" name="code" bean="${course}" value="" class="form-control" />
	         </div>
	    </div>
--%>
        <div class="form-group">
            <label for="isVisible" class="col-md-2 control-label">Published </label>
             <div class="col-md-10 ${hasErrors(bean:course,field:'isVisible', 'has-warning')}">
                    <div class="form-checkbox"><f:widget bean="${course}" property="isVisible" class="form-check-input" /></div>
             </div>
        </div>
       

        <div class="form-group">
            <label for="description" class="col-md-2 control-label">Welcome page </label>
             <div class="col-md-10">
                <ckeditor:editor name="welcomePage" toolbar="custom" height="300px" width="100%">

                </ckeditor:editor>
             </div>
        </div>

        <div class="form-group">
            <label for="description" class="col-md-2 control-label">Staff page </label>
             <div class="col-md-10">
                <ckeditor:editor name="staffPage" toolbar="custom" height="300px" width="100%">

                </ckeditor:editor>
             </div>
        </div>


    </div>

grails-app/views/course/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <ckeditor:resources/>
    </head>
    <body>

        <p><g:link controller="course" action="index">Courses</g:link> > Create Course</p>  

       <div class="panel panel-primary">
            <div class="panel-heading"><g:message code="default.create.label" args="[entityName]" /></div>
            <div class="panel-body">
                <ul class="errors" role="alert">
                <g:hasErrors bean="${course}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${course}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
                    </div>
                </g:hasErrors>
                
                </ul>

                <g:form url="[resource:course, action:'save']" class="form-horizontal" method="POST" >
                    <g:hiddenField name="version" value="${course?.version}" />

                    <fieldset class="form">
                        <g:render template="form_fields_create"/>
                    </fieldset>
                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'default.button.create.label', default: 'Create')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Create</button>
                        <g:link controller="course" action="index" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link>                      
                    </div>
                </g:form>
            </div>
        </div>

    </body>
</html>

grails-app/views/course/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
        <ckeditor:resources/>
    </head>
    <body>

        <div class="panel panel-primary">
            <div class="panel-heading"><g:message code="default.edit.label" args="[entityName]" /></div>
            <div class="panel-body">
                <ul class="errors" role="alert">
                <g:hasErrors bean="${course}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${course}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
                    </div>
                </g:hasErrors>
                
                </ul>

                <g:form url="[resource:course, action:'update']" class="form-horizontal" method="PUT" >
                    <g:hiddenField name="version" value="${course?.version}" />

                    <fieldset class="form">
                        <g:render template="form_fields"/>
                    </fieldset>
                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'default.button.update.label', default: 'Update')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Update</button>
  
                        <g:link controller="course" action="index" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link>
                    </div>
                </g:form>
            </div>
        </div>
      
    </body>
</html>

grails-app/views/course/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>

        <div  role="main">
            <p>Courses ></p>   
        <div class = "title_left">
            <h3>Courses</h3>
        </div>
        <div class = "title_right">
            <sec:ifAnyGranted roles="ROLE_ADMIN">
            <g:link class="create" action="create" class="btn btn-nav">New course</g:link>
            </sec:ifAnyGranted>
        </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <sec:ifAnyGranted roles="ROLE_ADMIN">                 
                    <%--<g:sortableColumn property="name" title="Name" />--%>
                    <th><div class="name-header">Name</div></th>
                    <th><div class="action-header">Action</div></th>
                    </sec:ifAnyGranted>
                </tr>
            </thead>
            <tbody>
                <g:each in="${courseList.sort{it.orderNo}}" status="i" var="courseInstance">
                <g:if test="${courseInstance.isVisible || sec.loggedInUserInfo(field:'authorities') == '[ROLE_ADMIN]'}">
                    <tr>                  
                        <td><g:link action="show" id="${courseInstance.id}">${fieldValue(bean: courseInstance, field: "name")}</g:link></td>
                        <td>
                        <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <div class="action">
                        <div class="dropdown">
                        <button class="dropbtn" type="button" data-toggle="dropdown">Select <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><g:link action="show" id="${courseInstance.id}">List modules</g:link></li>
                            <li><g:link controller="module" class="create" action="create" params="[course:courseInstance.id]">New module</g:link></li>
                            <li><g:link action="edit" id="${courseInstance.id}">Edit course</g:link></li>
                            <li>
                            <g:form id="${courseInstance.id}" method="DELETE">
<%--
                            <g:actionSubmit class="delete-button" action="delete" value="Delete course" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
--%>
                            <p:renderCourseDeleteLink curCourse="${courseInstance}"/>
                            </g:form>
                            </li>
                        </ul>
                        </div>
                        </div>
                        </sec:ifAnyGranted>
                        </td>
                    </tr>
                </g:if>    
                </g:each>
            </tbody>
        </table>
<%--
        <div class="pagination">
            <p:bootstrapPagination total="${courseCount ?: 0}" domainBean="uk.ac.ed.bric.elearn.vle.Course" />
        </div>
--%>
    </body>
</html>

grails-app/views/course/notEnrolled.gsp
<!doctype html>
<html>
    <head>
        <title>Not Enrolled</title>
        <meta name="layout" content="main">
        <g:if env="development"><asset:stylesheet src="errors.css"/></g:if>
    </head>
    <body>
        <p><b>${course.name}</b></p>
        <p>You are not enrolled on this course.</p>
        <p>If you think this is an error, please contact the course administrators.</p>
    </body>
</html>

grails-app/views/course/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div role="main">
            <p><g:link controller="course" action="index">Courses</g:link> > <f:display bean="course" property="name" /></p>
        <div class = "title_left">
            <h3><%--Modules for course:<br/>--%> <f:display bean="course" property="name" /></h3>
            <ul>
            <li><g:link controller="course" action="showWelcomePage" id="${course.id}">Welcome</g:link></li>
            <li><g:link controller="course" action="showStaffPage" id="${course.id}">Course Staff</g:link></li>
            </ul>
        </div>
        <div class = "title_right">
            <div class ="course_pages">
            <%--
            <ul>
            <li><g:link controller="course" action="showWelcomePage" id="${course.id}">Welcome</g:link></li>
            <li><g:link controller="course" action="showStaffPage" id="${course.id}">Course Staff</g:link></li>
            </ul>
            --%>
            </div>
            <sec:ifAnyGranted roles="ROLE_ADMIN"> 
            <g:link controller="module" class="create" action="create" params="[course:course.id]" class="btn btn-nav">New module</g:link>
            </sec:ifAnyGranted>
        </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>    
                    <%--<g:sortableColumn property="name" title="Modules" />--%>
                    <th><div class="name-header">Modules</div></th>
                    <sec:ifAnyGranted roles="ROLE_ADMIN">   
                    <th><div class="action-header">Action</div></th>
                    </sec:ifAnyGranted>
                </tr>
            </thead>
            <tbody>
                <g:each in="${course.modules.sort{it.orderNo}}" status="i" var="moduleInstance">
                <g:if test="${moduleInstance.isVisible || sec.loggedInUserInfo(field:'authorities') == '[ROLE_ADMIN]'}">
                    <tr>
                        <td>
                        <sec:ifAnyGranted roles="ROLE_ADMIN"> 
                            ${moduleInstance.orderNo}. <g:link controller="module" action="show" id="${moduleInstance.id}">${moduleInstance.name}</g:link>
                        </sec:ifAnyGranted>
                        <sec:ifAnyGranted roles="ROLE_USER">
                             ${moduleInstance.orderNo}. <g:link controller="module" action="studentView" id="${moduleInstance.id}">${moduleInstance.name}</g:link>
                        </sec:ifAnyGranted>
                        </td>
                        <td>
                        <sec:ifAnyGranted roles="ROLE_ADMIN"> 
                        <div class="action">
                        <div class="dropdown">
                        <button class="dropbtn" type="button" data-toggle="dropdown">Select <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><g:link controller="module" action="show" id="${moduleInstance.id}">List lectures</g:link></li>
                            <li><g:link controller="lecture" class="create" action="create" params="[module:moduleInstance.id]">New lecture</g:link></li>
                            <li><g:link controller="module" action="studentView" id="${moduleInstance.id}">View module</g:link></li>
                            <li><g:link controller="module" action="edit" id="${moduleInstance.id}">Edit module</g:link></li>
                            <li><g:form controller="module" id="${moduleInstance.id}" method="DELETE">
<%--
                                <g:actionSubmit class="delete-button" action="delete" value="Delete module" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
--%>
                                <p:renderModuleDeleteLink curModule="${moduleInstance}"/>
                            </g:form></li>
                        </ul>
                        </div>                            
                        </div>
                        </sec:ifAnyGranted>
                        </td>
                    </tr>
                </g:if>
                </g:each>
            </tbody>
        </table>
<%--
        <div class="pagination">
            <p:bootstrapPagination total="${course.modules?.size() ?: 0}" domainBean="uk.ac.ed.bric.elearn.vle.Course" />
        </div>
--%>
        <%--to do: make these active links at the appropriate times--%>
        <g:if test="${course.id == 1}">
        <ul>
        <li>Practice assessment (You can only take this assessment when you have achieved a 100% mark in all the course tests)</li>
        <li>Exit assessment (You can only take this assessment when you have completed the practice assessment)</li>
        <li>Exit survey (You must complete this before you can be given the course certificate)</li>
        <li>Course certificate</li>
        </ul>
        </g:if>
        <i class="fa fa-envelope"></i> <a href="mailto:Imaging.Academy@ed.ac.uk">Contact user support</a></li>
    </body>
</html>

grails-app/views/course/showStaffPage.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div role="main">
            <p><g:link controller="course" action="index">Courses</g:link> > <g:link controller="course" action="show" id="${course.id}"><f:display bean="course" property="name" /></g:link> > Course Staff </p>
            <h3><%--Course:<br/>--%><f:display bean="course" property="name" /></h3>
        <div class = "title_left">
        </div>
        <div class = "title_right">
        </div>
        </div>

        <div class="showContent">
            <p><f:display bean="course" property="staffPage" /></p>
        </div>
    </body>
</html>

grails-app/views/course/showWelcomePage.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div  role="main">
            <p><g:link controller="course" action="index">Courses</g:link> > <g:link controller="course" action="show" id="${course.id}"><f:display bean="course" property="name" /></g:link> > Welcome </p>
            <h3><%--Course:<br/>--%><f:display bean="course" property="name" /></h3>
        <div class = "title_left">
        </div>
        <div class = "title_right">
        </div>
        </div>

        <div class="showContent">
            <p><f:display bean="course" property="welcomePage" /></p>
        </div>

    </body>
</html>