grails-app/domain/uk/ac/ed/bric/elearn/vle/QuestionGroup.groovy
package uk.ac.ed.bric.elearn.vle

class QuestionGroup {

    Integer orderNo
    Boolean isVisible
	String questionGroupText

    static belongsTo =  [ owner : Test ]
    static hasMany = [ questions : Question, qGImages : QGImage ]

    static constraints = {
    	orderNo blank:false, nullable:false, unique:['owner']
   		isVisible blank:true, nullable:true
    	questionGroupText blank:false, nullable:false
    }

    static mapping = {
		questionGroupText type: "text"
	}

    String toString() {
        if (owner)
        {
            String qgname = owner.name + ": " + orderNo
            return qgname
        }
    }

}

grails-app/controllers/uk/ac/ed/bric/elearn/vle/QuestionGroupController.groovy
package uk.ac.ed.bric.elearn.vle

import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import uk.ac.ed.bric.elearn.vle.ImageCommand

@Transactional(readOnly = true)
class QuestionGroupController {

    static allowedMethods = [save: "POST", update: "PUT", delete: ["GET","DELETE"]]

    def fileService

    @Secured('ROLE_ADMIN')
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond QuestionGroup.list(params), model:[questionGroupCount: QuestionGroup.count()]
    }

    @Secured('ROLE_ADMIN')
    def show(QuestionGroup questionGroup) {
        respond questionGroup
    }

    @Secured('ROLE_ADMIN')
    def create() {
        //respond new QuestionGroup(params)
        def test = Test.get(params.testId)
        if(test == null) {
            flash.error = message(code: 'cannot.find.test')
            return
        }
      
        respond new QuestionGroup(params), model:[ test:test ]
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def save(QuestionGroup questionGroup) {
        if (questionGroup == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        def test = Test.get(params.ownerId)

        if (questionGroup.hasErrors()) {
            transactionStatus.setRollbackOnly()
            //respond questionGroup.errors, view:'create'
            respond questionGroup.errors, view:'create', model:[ questionGroup:questionGroup, test:test, lecture:test.lecture, module: test.lecture.module, course:test.lecture.module.course ]
            return
        }

        questionGroup.save flush:true

        flash.message = message(code: 'default.created.message', args: [message(code: 'questionGroup.label', default: 'Question Group'), questionGroup.id])
        //render view:"show", model:[ test:test]
        redirect controller: "test", action:"show", id: test.id
    }

    @Secured('ROLE_ADMIN')
    def edit(QuestionGroup questionGroup) {
        respond questionGroup
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def update(QuestionGroup questionGroup) {

        Test test = questionGroup.owner

        if (questionGroup == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (questionGroup.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond questionGroup.errors, view:'edit'
            return
        }

        questionGroup.save flush:true

        if (questionGroup.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond questionGroup.errors, view:'edit'
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'questionGroup.label', default: 'Question Group'), questionGroup.id])
        forward controller: "test", action: "show", id: test.id

//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.updated.message', args: [message(code: 'questionGroup.label', default: 'QuestionGroup'), questionGroup.id])
//                redirect questionGroup
//            }
//            '*'{ respond questionGroup, [status: OK] }
//        }
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def delete(QuestionGroup questionGroup) {

        Test test = questionGroup.owner

        if (questionGroup == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        test.removeFromQuestionGroups(questionGroup)
        questionGroup.delete flush:true

        flash.message = message(code:"questionGroup.deleted")
        forward controller:"test", action:"show", id: test.id

//       request.withFormat {
//           form multipartForm {
//               flash.message = message(code: 'default.deleted.message', args: [message(code: 'questionGroup.label', default: 'QuestionGroup'), questionGroup.id])
//               redirect action:"index", method:"GET"
//           }
//           '*'{ render status: NO_CONTENT }
//        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionGroup.label', default: 'QuestionGroup'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def uploadQuestionGroupImage(ImageCommand command) {

        QuestionGroup questionGroup = QuestionGroup.get(params.questionGroupId)
        Test test = questionGroup.owner

        if(command.hasErrors()) {
            render view: 'edit', model:[ questionGroup:questionGroup, imageCommand:command ]
            return
        }
 
        fileService.saveFile3(command, questionGroup)
        render view: 'edit', model:[ questionGroup:questionGroup ]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def deleteQuestionGroupImage() {

        QGImage qGImage = QGImage.get(params.int('qGImageId'))
        
        if (qGImage == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        QuestionGroup questionGroup = qGImage.questionGroup
        fileService.deleteQuestionGroupImage(questionGroup, qGImage)

        if(questionGroupImageSaveFail(qGImage)) {
            render template:"images", model:[ questionGroup:questionGroup ]
            return     
        }

        render template:"images", model:[ questionGroup:questionGroup ]

    }

    @Transactional
    def questionGroupImageSaveFail(domainObject) {
        def result = true
        if(domainObject.hasErrors()) {
            transactionStatus.setRollbackOnly()
            flash.ajaxerror = errorsToString(domainObject) 
            result = true
        } else {
            result = false
        }
        return result
    }

    def errorsToString(domainObject) {
        def message = new StringBuilder()
        for(fieldErrors in domainObject.errors) {
            for(error in fieldErrors.allErrors) {
                message.append("\n\t").append(messageSource.getMessage(error, Locale.getDefault()))
            }
        }
        message.toString()       
    }

}

grails-app/views/questionGroup/_form.gsp
<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: questionGroup, field: 'owner', 'error')} required">
		<label for="questionGroup" class="control-label col-md-3">
			Test
			<span class="required-indicator">*</span>
		</label>
		<div class="col-md-9">
             <f:widget bean="${questionGroup}" property="owner" class="form-check-input" />
		</div>
	</div>
</div>

<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: questionGroup, field: 'orderNo', 'error')} required">
		<label for="orderNo" class="control-label col-md-3">
			Order
			<span class="required-indicator">*</span>
		</label>
		<div class="col-md-2">
			<g:field name="orderNo" type="number" min="1" max="100" value="${questionGroup?.orderNo}" required=""  class="form-control"/>
		</div>
	</div>
</div>

<%--
<div class="form-group">
    <label for="isVisible" class="col-md-3 control-label">Published </label>
    <div class="col-md-9 ${hasErrors(bean:questionGroup, field:'isVisible', 'has-warning')}">
        <div class="form-checkbox"><f:widget bean="${questionGroup}" property="isVisible" class="form-check-input" /></div>
    </div>
</div>
--%>

<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: questionGroup, field: 'questionGroupText', 'error')} " required>
		<label for="questionText"  class="control-label col-md-3">
			<g:message code="question.questionGroupText.label" default="Question Group Text " /><span class="required-indicator">*</span>
		</label>
	<div class="col-md-9">
		<ckeditor:editor name="questionGroupText" toolbar="custom" height="200px" width="100%">
	 	${questionGroup?.questionGroupText}
		</ckeditor:editor>
	</div>
</div>

grails-app/views/questionGroup/_images.gsp
<div id="optionsDiv">
	<g:if test="${flash.ajaxerror}">
		<div class="alert alert-dismissable alert-danger">
			<button type="button" class="close" data-dismiss="alert">×</button>
			${flash.ajaxerror}
		</div>
	</g:if>

	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-8"><p><strong>Current images:</strong></p></div>
	</div>
		
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-9">
			<g:if test="${questionGroup.qGImages}">
				<ul class="list-group">
					<g:each in="${questionGroup.qGImages}" var="qGImage">
					 	<li class="list-group-item">
<%--
					 	${qGImage.filePath} (display text: ${qGImage.filePath})
--%>
					 	<img src="<g:resource base="${grailsApplication.config.external.webserver}" dir="images" file="${qGImage.fileName}"/>" width="100" />

					 	<div class="delete-buttons-images">
					 	<a href="#" class="pull-right text-danger" onClick="deleteOption('${qGImage?.id}')">
					 	<button class="btn btn-danger">
					 	<i class="fa fa-trash-o" aria-hidden="true"></i> Delete
					 	</button>
					 	</a>
					 	</div>

						</li>
					</g:each>
				</ul>
			</g:if>
			<g:else>
				<p><em>No images added yet</em></p>
			</g:else>
		</div>
	</div>
</div>

grails-app/views/questionGroup/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'questionGroup.label', default: 'QuestionGroup')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <ckeditor:resources/>
    </head>
    <body>

        <g:render template="/shared-templates/test_head"/>
        
        <div class="panel panel-primary">
            <div class="panel-heading">Create Question Group</div>
                <div class="panel-body">

                    <g:hasErrors bean="${this.questionGroup}">
                    <div class="alert alert-danger">
                        <p>Error(s)</p>
                        <ul  role="alert">
                            <g:eachError bean="${this.questionGroup}" var="error">
                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                            </g:eachError>
                        </ul>
                    </div>
                    </g:hasErrors>
   
                    <g:form class="form-horizontal" url="[resource:questionGroup, action:'save']">

                    <g:hiddenField name="ownerId" value="${test?.id}"/>
                    <g:hiddenField name="isVisible" value="false"/>
                    <fieldset class="form">
                        <g:render template="form"/>
                    </fieldset>
                    <br/>

                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'default.button.create.label', default: 'Create')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Create</button>
                        <g:link controller="test" action="show" id="${test.id}" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link> 
                    </div>

                    </g:form>
                </div>  
            </div>
        </div>

    </body>
</html>

grails-app/views/questionGroup/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'questionGroup.label', default: 'QuestionGroup')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
        <ckeditor:resources/>
        <script type="text/javascript">
            
            function deleteOption(qGImageId) {
                var params = {qGImageId:qGImageId}
                handleOption(params,"${grailsApplication.config.vle.url}/QuestionGroup/deleteQuestionGroupImage")
            };

            function handleOption(params, action) {
                var data = $.param(params)
                var response
                $.post(action,data, function(response) {
                    $('#optionsDiv').html( response )
                })  
                .fail(function() {
                    $( "#optionsDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };
    
        </script>
    </head>
    <body>

        <g:render template="/shared-templates/test_head" model="['test':questionGroup.owner]"/>
        <div class="panel panel-primary">
            <div class="panel-heading">Edit Question Group</div>
            <div class="panel-body">
                <ul class="errors" role="alert">
                <g:hasErrors bean="${questionGroup}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${questionGroup}" var="error">
                            <p <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></p>
                        </g:eachError>
                    </div>
                </g:hasErrors>              
                </ul>
            
                <g:form role="form" class="form-horizontal" url="[resource:questionGroup, action:'update']" method="PUT">

                <fieldset class="form">
                    <g:render template="form"/>
                </fieldset>
                <BR>
                <fieldset class="buttons pull-right">
              
                <g:link controller="test" action="show" id="${questionGroup.owner.id}" class="btn btn-default" ><i class='fa fa-times-circle' aria-hidden='true'></i> Cancel</g:link>

                <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Update</button>
          
                </fieldset>
                </g:form>
                <br/>
                <hr/>

                <ul class="errors" role="alert">
                <g:hasErrors bean="${imageCommand}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${imageCommand}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
                    </div>
                </g:hasErrors>
                
                </ul>

                <div role="main">
                <div class = "title_left">
                <g:uploadForm action="uploadQuestionGroupImage">
                    <input type="file" class="btn btn-default" name="uploadedQuestionGroupImage" />
                    <br/>
                    <input type="submit" value="Upload" class="btn btn-primary"/>
                    <g:hiddenField name="questionGroupId" value="${questionGroup.id}"/>
                </g:uploadForm>
                </div>
                <div class = "title_right-test">
                <g:link controller="test" id="${questionGroup.owner.id}" class="show" action="show" class="btn btn-nav">Questions</g:link>
                </div>
            </div>

            <br/>

            <g:render template="images" bean="${questionGroup}"/>

        </div>        
    </body>
</html>

grails-app/views/questionGroup/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'questionGroup.label', default: 'QuestionGroup')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-questionGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-questionGroup" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${questionGroupList}" />

            <div class="pagination">
                <g:paginate total="${questionGroupCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/questionGroup/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'questionGroup.label', default: 'QuestionGroup')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-questionGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-questionGroup" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="questionGroup" />
            <g:form resource="${this.questionGroup}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.questionGroup}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>