grails-app/domain/uk/ac/ed/bric/elearn/vle/Choice.groovy
package uk.ac.ed.bric.elearn.vle

class Choice {

    Integer choiceOrder
	String choiceText
    Question owner
    Boolean choiceStatus 

	static belongsTo =  Question

	static constraints = {
    	choiceOrder blank:false, nullable:false, unique:['owner']
    	choiceText blank:false, nullable:false
        choiceStatus blank:true, nullable:true
    }

    static mapping = {
		choiceText type: "text"
	}

}

grails-app/domain/uk/ac/ed/bric/elearn/vle/Question.groovy
package uk.ac.ed.bric.elearn.vle

class Question {

    Integer orderNo
    Boolean isVisible
	String questionText

    static belongsTo = [ owner : QuestionGroup ]
    static hasMany = [ choices: Choice ]

    static constraints = {
    	orderNo blank:false, nullable:false, unique:['owner']
   		isVisible blank:true, nullable:true
    	questionText blank:false, nullable:false
    }

    static mapping = {
		questionText type: "text"
	}
}

grails-app/controllers/uk/ac/ed/bric/elearn/vle/QuestionController.groovy
package uk.ac.ed.bric.elearn.vle

import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class QuestionController {

    def messageSource
    def testService

    static allowedMethods = [save: "POST", update: "PUT", delete: ["GET","DELETE"]]

    @Secured('ROLE_ADMIN') 
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Question.list(params), model:[questionCount: Question.count()]
    }

    @Secured('ROLE_ADMIN') 
    def show(Question question) {
        respond question
    }

    @Secured('ROLE_ADMIN') 
    def create() {
        def test = Test.get(params.testId)
        if(test == null) {
            flash.error = message(code: 'cannot.find.test')
            return
        }
      
        respond new Question(params), model:[ test:test ]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def save(Question question) {
        if (question == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        def questionGroup = QuestionGroup.get(params.owner.id)
        def test = Test.get(params.ownerOwnerId)

        if(questionGroup == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return    
        }

        question.owner = questionGroup

        if (question.hasErrors()) {
            transactionStatus.setRollbackOnly()
            //respond question.errors, view:'create', model:[ test:test ]
            respond question.errors, view:'create', model:[ questionGroup:questionGroup, test:test, lecture:test.lecture, module: test.lecture.module, course:test.lecture.module.course ]
            return
        }

        question.save flush:true

        if (question.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond question.errors, view:'create', model:[ questionGroup:questionGroup, test:test ]
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'question.label', default: 'Question'), question.id])
        render view:"show", model:[ question:question, questionGroup:questionGroup, test:test, choiceList:[]]
        //render view:"show", model:[ question:question, test:test, choiceList:[]]
        //render view:"show", model:[ question:question ]
    }

    @Secured('ROLE_ADMIN') 
    def edit(Question question) {
        //respond question
        respond question, model:[ choiceList:question.choices.sort{it.choiceOrder} ]
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def update(Question question) {
        if (question == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (question.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond question.errors, view:'edit'
            return
        }

        question.save flush:true

        if (question.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond question.errors, view:'edit', model:[ test:test ]
            return
        }


        flash.message = message(code: 'default.updated.message', args: [message(code: 'question.label', default: 'Question'), question.id])
        forward controller: "test", action: "show", id: question.owner.owner.id

   //     request.withFormat {
   //         form multipartForm {
   //             flash.message = message(code: 'default.updated.message', args: [message(code: 'question.label', default: 'Question'), question.id])
   //             redirect question
   //         }
   //         '*'{ respond question, [status: OK] }
   //     }
    }

    @Secured('ROLE_ADMIN') 
    @Transactional
    def delete(Question question) {

        QuestionGroup questionGroup = question.owner

        if (question == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

//        if(testService.isTargetQuestion(question)) {
//            flash.error = message(code:"cannot.delete.target.question")
//            forward controller:"test", action:"show", id: test.id
//            return
//        }

        questionGroup.removeFromQuestions(question)
        question.delete flush:true

        flash.message = message(code:"question.deleted")
        forward controller:"test", action:"show", id: questionGroup.owner.id

//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.deleted.message', args: [message(code: 'question.label', default: 'Question'), question.id])
//                redirect action:"index", method:"GET"
//            }
//            '*'{ render status: NO_CONTENT }
//        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'question.label', default: 'Question'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def addChoice() {
        
        def question = Question.get(params.questionId)
        if(question == null) {
           render status:500
           return 
        }
        
        def choiceOrder = params.int('choiceOrder')
        def choiceText = params.choiceText
        def choiceStatus = params.boolean('choiceStatus')
        def choice = new Choice(owner:question, choiceOrder:choiceOrder, choiceText:choiceText, choiceStatus:choiceStatus )

        def choiceList = testService.listChoicesForQuestion(question)

        if(choice.hasErrors()) {
            transactionStatus.setRollbackOnly()
            flash.ajaxerror = handlChoiceErrors(choice)
            render template:"choices", model:[choiceList:choiceList, question:question]
            return  
        } 

        choice.save flush:true
        if(choice.hasErrors()) {
            transactionStatus.setRollbackOnly()
            flash.ajaxerror = handlChoiceErrors(choice)
            render template:"choices", model:[choiceList:choiceList, question:question]
            return
        }

        choiceList = testService.listChoicesForQuestion(question)
        render template:"choices", model:[choiceList:choiceList, question:question]
    }

    @Secured('ROLE_ADMIN')
    @Transactional
    def deleteChoice() {
        def choice = Choice.get(params.choiceId)
        
        if(choice == null) {
            render status:500
            return
        }
        
        def question = Question.get(choice.owner.id)
        if(question == null) {
            render status:500
            return
        }
        def choiceList = testService.listChoicesForQuestion(question)
        
        choice.delete flush:true
        if(choice.hasErrors()) {
            transactionStatus.setRollbackOnly()
            flash.ajaxerror = handlChoiceErrors(choice)
            render template:"choices", model:[choiceList:choiceList, question:question]
            return
        }

        choiceList = testService.listChoicesForQuestion(question)
        render template:"choices", model:[choiceList:choiceList, question:question]
    }

    def handlChoiceErrors(choice) {
        def message = new StringBuilder()
        for(fieldErrors in choice.errors) {
            for(error in fieldErrors.allErrors) {
                message.append("\n\t").append(messageSource.getMessage(error, Locale.getDefault()))
            }
        }
        message.toString()   
    }

}

grails-app/views/question/_choices.gsp
<div id="choicesDiv">
<g:if test="${flash.ajaxerror}">
			<div class="alert alert-dismissable alert-danger">
				<button type="button" class="close" data-dismiss="alert">×</button>
				${flash.ajaxerror}
			</div>
	</g:if>

	<form class="form-inline">
		
	    <div  role="main">
        	<div class = "title_left">
			<h4>Choices</h4>
			</div>
            <div class = "title_right-test">
            <g:link controller="test" id="${question.owner.owner.id}" class="show" action="show" class="btn btn-nav">Questions</g:link>
            </div>
        </div>

        <div class="listChoices"> 
		<ul class="list-group">
		<g:each in="${choiceList}" var="choice">
		 	<li class="list-group-item">

		 	<a href="#/" title="Delete choice" data-toggle="tooltip"  onclick="deleteChoice('${choice?.id}')"><i class="fa fa-trash-o fa-lg text-danger pull-right" aria-hidden="true"></i></a>
		 	   
		 	   <p:renderChoice choice="${choice}"/>
		 	
		 	</li>
		</g:each>
		</ul>
		</div>
		
		<g:if test="${choiceList.size() > 0}">
			<g:set var="choiceOrder" value="${choiceList.size()+1}"/>
		</g:if>
		<g:else>
			<g:set var="choiceOrder" value="1"/>
		</g:else>

	Add Choice:<br/>
	  <div class="form-group">
	    <label for="choiceOrderLabel">Order</label>
	    <g:field name="choiceOrderField" type="number" min="1" max="10" size="2" value="${choiceOrder}" class="form-control"/> 
	  </div>
	  
	  <div class="form-group">
	    <label for="choiceText">Text</label>
	    <g:field name="choiceTextField" type="text" size="50" class="form-control"/>
	  </div>

	  <div class="form-group">
	    <label for="choiceStatus">Correct?&nbsp;</label>
	 	<g:checkBox name="choiceStatusField" class="form-check-input"/>
	  </div>

  	 <a href="#/" title='Add choice' data-toggle='tooltip' class="btn btn-primary pull-right"" onclick="addChoice('${question?.id}')"><i class="fa fa-plus-square-o fa-lg" aria-hidden="true"></i> 
                 </a>
	</form>

</div>
<BR>

grails-app/views/question/_form.gsp
<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: question, field: 'owner', 'error')} required">
		<label for="questionGroup" class="control-label col-md-3">
			Question Group
			<span class="required-indicator">*</span>
		</label>
		<div class="col-md-9">
             <f:widget bean="${question}" property="owner" class="form-check-input" />
		</div>
	</div>
</div>

<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: question, field: 'orderNo', 'error')} required">
		<label for="orderNo" class="control-label col-md-3">
			Order
			<span class="required-indicator">*</span>
		</label>
		<div class="col-md-2">
			<g:field name="orderNo" type="number" min="1" max="100" value="${question?.orderNo}" required=""  class="form-control"/>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="fieldcontain ${hasErrors(bean: question, field: 'questionText', 'error')} " required>
		<label for="questionText"  class="control-label col-md-3">
			<g:message code="question.questionText.label" default="Question Text " /><span class="required-indicator">*</span>
		</label>
	<div class="col-md-9">
		<ckeditor:editor name="questionText" toolbar="custom" height="200px" width="100%">
	 	${question?.questionText}
		</ckeditor:editor>
	</div>
</div>

grails-app/views/question/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'question.label', default: 'Question')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <ckeditor:resources/>
    </head>
    <body>

        <g:render template="/shared-templates/test_head"/>
        
        <div class="panel panel-primary">
            <div class="panel-heading"><g:message code="default.create.label" args="[entityName]" /></div>
                <div class="panel-body">

                    <g:hasErrors bean="${this.question}">
                    <div class="alert alert-danger">
                        <p>Error(s)</p>
                        <ul  role="alert">
                            <g:eachError bean="${this.question}" var="error">
                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                            </g:eachError>
                        </ul>
                    </div>
                    </g:hasErrors>
   
                    <g:form class="form-horizontal" url="[resource:question, action:'save']">

                    <g:hiddenField name="ownerOwnerId" value="${test?.id}"/>
                    <g:hiddenField name="isVisible" value="false"/>
                    <fieldset class="form">
                        <g:render template="form"/>
                    </fieldset>
                    <br/>

                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-primary pull-right" value="${message(code: 'default.button.create.label', default: 'Create')}" ><i class="fa fa-floppy-o" aria-hidden="true"></i> Create</button>
                        <g:link controller="test" action="show" id="${test.id}" class="btn btn-default pull-right"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancel</g:link> 
                    </div>

                    </g:form>
                </div>  
            </div>
        </div>

    </body>
</html>

grails-app/views/question/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'question.label', default: 'Question')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
        <ckeditor:resources/>
    </head>
    <body>

        <g:render template="/shared-templates/test_head" model="['test':question.owner.owner]"/>
        
        <div class="panel panel-primary">
            <div class="panel-heading">Edit Question</div>
            <div class="panel-body">
                <ul class="errors" role="alert">
                <g:hasErrors bean="${question}">
                    <div class="alert alert-dismissable alert-danger">
                        <h4>Please fix the following error(s)</h4>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <g:eachError bean="${question}" var="error">
                            <p <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></p>
                        </g:eachError>
                    </div>
                </g:hasErrors>
                </ul>
            
                <g:form role="form" class="form-horizontal" url="[resource:question, action:'update']" method="PUT">

                <fieldset class="form">
                    <g:render template="form"/>
                </fieldset>
                <br/>
                <fieldset class="buttons pull-right">
              
                <g:link controller="test" action="show" id="${question.owner.owner.id}" class="btn btn-default" ><i class='fa fa-times-circle' aria-hidden='true'></i> Cancel</g:link>

                <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Update</button>
          
                </fieldset>
                </g:form>
                <br/>
                <br/>
                <hr>

                <g:render template="choices"/>

                <hr> 
            </div>
        </div>

        <script type="text/javascript">

            function deleteChoice(choiceId) {
                var params = {choiceId:choiceId}
                var data = $.param(params)
                $.post("${grailsApplication.config.vle.url}/question/deleteChoice", data, function(response) {
                    $('#choicesDiv').html( response )   
                })
                .fail(function() {
                    $( "#choicesDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };

            function addChoice(questionId) {
               
                var choiceOrder = $('#choiceOrderField').val()
                var choiceText = $('#choiceTextField').val()
                if ($('#choiceStatusField').prop('checked'))
                {
                    var choiceStatus = "true"
                }
                else
                {
                    var choiceStatus = "false"
                }                  

                var params = {questionId:questionId, choiceOrder:choiceOrder, choiceText:choiceText, choiceStatus:choiceStatus}
                var data = $.param(params)
                var response
                $.post("${grailsApplication.config.vle.url}/question/addChoice",data, function(response) {
                    $('#choicesDiv').html( response )
                })  
                .fail(function() {
                    $( "#choicesDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };

            $(document).ready(function() {
              
            });

        </script>

    </body>
</html>

grails-app/views/question/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'question.label', default: 'Question')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-question" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-question" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${questionList}" />

            <div class="pagination">
                <g:paginate total="${questionCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/question/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'question.label', default: 'Question')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>

        <script type="text/javascript">

            function deleteChoice(choiceId) {
                var params = {choiceId:choiceId}
                var data = $.param(params)
                $.post("/question/deleteChoice", data, function(response) {
                    $('#choicesDiv').html( response )   
                })
                .fail(function() {
                    $( "#choicesDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };
            
            function addChoice(questionId) {
               
                var choiceOrder = $('#choiceOrderField').val()
                var choiceText = $('#choiceTextField').val()
                //var choiceStatus = $('#choiceStatusField').val()
                if ($('#choiceStatusField').prop('checked'))
                {
                    var choiceStatus = "true"
                }
                else
                {
                    var choiceStatus = "false"
                }
                var params = {questionId:questionId, choiceOrder:choiceOrder, choiceText:choiceText, choiceStatus:choiceStatus}
                var data = $.param(params)
                var response
                $.post("/question/addChoice",data, function(response) {
                    $('#choicesDiv').html( response )
                })  
                .fail(function() {
                    $( "#choicesDiv" ).html("<p><h3 class='text-danger'>An unexpected error occurred. Please contact user support.</h3></p>")
                })   
            };

        </script>

    </head>
    <body>

<%--
        <a href="#show-question" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-question" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="question" />
            <g:form resource="${this.question}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.question}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
--%>

<%--
        <g:render template="/shared-templates/test_head"/>
--%>

        <div  role="main">
            <div class = "title_left">
            <h4>Question Group:</h4> <f:display bean="${questionGroup}" property="questionGroupText" />
<%--
            ${questionGroup.questionGroupText}
--%>
            <h4>Question ${question.orderNo}</h4>
            <ul>
                <g:if test="${question?.questionText}">
                <li class="fieldcontain">
                    
                        <span class="property-value" aria-labelledby="questionText-label">
                        ${raw(question.questionText)}
                        
                        </span>
                    
                </li>
                </g:if>
            </ul>
            </div>
<%--
            <div class = "title_right">

            <button class="btn"><g:link controller="test" id="${test.id}" class="show" action="show">Test</g:link></button>

            </div>
--%>
        </div>
<%--
        <div id="show-question" role="main">
            <ul>
                <g:if test="${question?.questionText}">
                <li class="fieldcontain">
                    
                        <span class="property-value" aria-labelledby="questionText-label">
                        ${raw(question.questionText)}
                        
                        </span>
                    
                </li>
                </g:if>
            </ul>
--%>   
            <hr>
          
        <div class="listChoices"> 
            <g:render template="choices"/>
           
        </div>

    </body>
</html>